
import {
  AdsItemComponent,
  AdsListComponent,
  AuthDialogComponent,
  CurrencyItemComponent,
  CurrencyListComponent,
  DashboardBlockComponent,
  DialogMessageComponent,
  DialogRequestComponent,
  ExchangeItemComponent,
  ExchangeListComponent,
  ICOItemComponent,
  ICOListComponent,
  ImupComponent,
  LogsBlockComponent,
  MarketItemComponent,
  MarketListComponent,
  NoContentComponent,
  PublicationItemComponent,
  PublicationListComponent,
  SectionItemComponent,
  SectionListComponent,
  StatusListComponent,
  UserItemComponent,
  UserListComponent,
  VideoListComponent,
} from './components'

export const COMPONENTS: any[] = [
  AdsItemComponent,
  AdsListComponent,
  AuthDialogComponent,
  CurrencyItemComponent,
  CurrencyListComponent,
  DashboardBlockComponent,
  DialogMessageComponent,
  DialogRequestComponent,
  ExchangeItemComponent,
  ExchangeListComponent,
  ICOItemComponent,
  ICOListComponent,
  ImupComponent,
  LogsBlockComponent,
  MarketItemComponent,
  MarketListComponent,
  NoContentComponent,
  PublicationItemComponent,
  PublicationListComponent,
  SectionItemComponent,
  SectionListComponent,
  StatusListComponent,
  UserItemComponent,
  UserListComponent,
  VideoListComponent,
]

export const ENTRY_COMPONENTS: any[] = [
  AuthDialogComponent,
  DialogMessageComponent,
  DialogRequestComponent,
]
