version: '3.3'

services:

  db:
    restart: unless-stopped
    image: postgres:10-alpine
    volumes:
      - data-volume:/var/lib/postgresql/data
      - ./sql/postgresql.conf:/etc/postgresql.conf:ro
      - ./sql/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_DB: bitjournal
      POSTGRES_USER: bitjournal
      POSTGRES_PASSWORD: bitjournal
    networks:
      default:
    ports:
      - 5432:5432
    command: postgres -c config_file=/etc/postgresql.conf

  api-main:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.main
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/environment
    networks:
      default:
    ports:
      - 8091:80

  api-raw:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.raw
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/environment
    networks:
      default:
    ports:
      - 8092:80

  api-ticker:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.ticker
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/environment
    networks:
      default:
    ports:
      - 8093:80

  api-front:
    restart: unless-stopped
    build: ./nginx
    links:
      - api-main
      - api-raw
      - api-ticker
    depends_on:
      - api-main
      - api-raw
      - api-ticker
    volumes:
      - ./api/assets:/www:ro
      - ./api/server.conf.d:/etc/nginx/server.conf.d:ro
      - ./api/server.dev.conf:/etc/nginx/server.conf:ro
    networks:
      default:
    ports:
      - 8081:80

  raw:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.main
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./raw/environment
    networks:
      default:
    ports:
      - 8090:80

  raw-front:
    restart: unless-stopped
    build: ./nginx
    links:
      - raw
    depends_on:
      - raw
    volumes:
      - ./raw/assets:/www:ro
      - ./raw/raw.conf:/etc/nginx/raw.conf:ro
      - ./raw/server.dev.conf:/etc/nginx/server.conf:ro
    networks:
      default:
    ports:
      - 8082:80

  admin:
    restart: unless-stopped
    build: ./nginx
    volumes:
      - ./admin/dist:/www:ro
      - ./admin/server.dev.conf:/etc/nginx/server.conf:ro
    networks:
      default:
    ports:
      - 8083:80

  portal-back:
    restart: unless-stopped
    build:
      context: ./portal
      dockerfile: Dockerfile.back
    environment:
      NODE_DEBUG: service
    networks:
      default:
    ports:
      - 8099:80

  portal-front:
    restart: unless-stopped
    build: ./nginx
    links:
      - portal-back
    depends_on:
      - portal-back
    volumes:
      - ./portal/dist/front:/www:ro
      - ./portal/server.dev.conf:/etc/nginx/server.conf:ro
    networks:
      default:
    ports:
      - 8080:80

volumes:
  data-volume:
