version: '3.3'

services:

  db:
    restart: unless-stopped
    image: postgres:10-alpine
    volumes:
      - data-volume:/var/lib/postgresql/data
      - ./sql/postgresql.conf:/etc/postgresql.conf:ro
      - ./sql/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_DB: bitjournal
      POSTGRES_USER: bitjournal
      POSTGRES_PASSWORD: bitjournal
    networks:
      default:
    command: postgres -c config_file=/etc/postgresql.conf

  api-main:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.main
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/environment
    networks:
      default:
    networks:
      default:

  api-raw:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.raw
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/environment
    networks:
      default:

  api-ticker:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.ticker
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/environment
    networks:
      default:

  api-front:
    restart: unless-stopped
    build: ./nginx
    links:
      - api-main
      - api-raw
      - api-ticker
    depends_on:
      - api-main
      - api-raw
      - api-ticker
    volumes:
      - ./api/assets:/www:ro
      - ./api/server.conf.d:/etc/nginx/server.conf.d:ro
      - ./api/server.conf:/etc/nginx/server.conf:ro
    networks:
      default:
      outside:
        ipv6_address: 2001:41d0:303:1f89:3:61b1:6a10:65
    ports:
      - 145.239.188.65:443:443

  raw:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.main
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./raw/environment
    networks:
      default:

  raw-front:
    restart: unless-stopped
    build: ./nginx
    links:
      - raw
    depends_on:
      - raw
    volumes:
      - ./raw/assets:/www:ro
      - ./raw/raw.conf:/etc/nginx/raw.conf:ro
      - ./raw/server.conf:/etc/nginx/server.conf:ro
    networks:
      default:
      outside:
        ipv6_address: 2001:41d0:303:1f89:3:61b1:6a10:66
    ports:
      - 145.239.188.66:443:443

  admin:
    restart: unless-stopped
    build: ./nginx
    volumes:
      - ./admin/dist:/www:ro
      - ./admin/server.conf:/etc/nginx/server.conf:ro
      - ./admin/ssl/ca.crt:/etc/nginx/ca.crt:ro
    networks:
      default:
      outside:
        ipv6_address: 2001:41d0:303:1f89:3:61b1:6a10:67
    ports:
      - 145.239.188.67:443:443

  portal-back:
    restart: unless-stopped
    build:
      context: ./portal
      dockerfile: Dockerfile.back
    networks:
      default:

  portal-front:
    restart: unless-stopped
    build: ./nginx
    links:
      - portal-back
    depends_on:
      - portal-back
    volumes:
      - ./portal/dist/front:/www:ro
      - ./portal/server.conf:/etc/nginx/server.conf:ro
    networks:
      default:
      outside:
        ipv6_address: 2001:41d0:303:1f89:3:61b1:6a10:64
    ports:
      - 145.239.188.64:443:443
      - 145.239.188.64:80:80

  # land:
  #   restart: unless-stopped
  #   build: ./nginx
  #   volumes:
  #     - ./land/www:/www:ro
  #     - ./land/server.conf:/etc/nginx/server.conf:ro
  #   networks:
  #     default:
  #     outside:
  #       ipv6_address: 2001:41d0:303:1f89:3:61b1:6a10:64
  #   ports:
  #     - 145.239.188.64:443:443
  #     - 145.239.188.64:80:80

networks:
  outside:
    external: true

volumes:
  data-volume:
