version: '3.4'

services:

  db:
    restart: unless-stopped
    build: ./sql
    volumes:
      - data-volume:/var/lib/postgresql/data
    env_file:
      - ./sql/environment
    networks:
      default:
    ports:
      - 5432:5432

  api-main-a:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.main
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/environment
    networks:
      default:

  api-main-b:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.main
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/environment
    networks:
      default:

  api-main-c:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.main
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/environment
    networks:
      default:

  api-ticker-a:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.ticker
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/environment
    networks:
      default:

  api-ticker-b:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.ticker
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/environment
    networks:
      default:

  api-ticker-c:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.ticker
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/environment
    networks:
      default:

  api-raw-a:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.raw
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./api/environment
    networks:
      default:

  api-front:
    restart: unless-stopped
    build: ./nginx
    links:
      - api-main-a
      - api-main-b
      - api-main-c
      - api-ticker-a
      - api-ticker-b
      - api-ticker-c
      - api-raw-a
    depends_on:
      - api-main-a
      - api-main-b
      - api-main-c
      - api-ticker-a
      - api-ticker-b
      - api-ticker-c
      - api-raw-a
    volumes:
      - ./api/assets:/www:ro
      - ./api/server.conf.d:/etc/nginx/server.conf.d:ro
      - ./api/server.conf:/etc/nginx/server.conf:ro
    networks:
      default:
      outside:
        ipv6_address: 2001:41d0:303:1f89:3:61b1:6a10:65
    ports:
      - 145.239.188.65:443:443

  raw-back-a:
    restart: unless-stopped
    build:
      context: ./raw
      dockerfile: Dockerfile.main
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./raw/environment
    networks:
      default:

  raw-back-b:
    restart: unless-stopped
    build:
      context: ./raw
      dockerfile: Dockerfile.main
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./raw/environment
    networks:
      default:

  raw-back-c:
    restart: unless-stopped
    build:
      context: ./raw
      dockerfile: Dockerfile.main
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./raw/environment
    networks:
      default:

  raw-front:
    restart: unless-stopped
    build: ./nginx
    links:
      - raw-back-a
      - raw-back-b
      - raw-back-c
    depends_on:
      - raw-back-a
      - raw-back-b
      - raw-back-c
    volumes:
      - ./raw/assets:/www:ro
      - ./raw/raw.conf:/etc/nginx/raw.conf:ro
      - ./raw/server.conf:/etc/nginx/server.conf:ro
    networks:
      default:
      outside:
        ipv6_address: 2001:41d0:303:1f89:3:61b1:6a10:66
    ports:
      - 145.239.188.66:443:443

  admin:
    restart: unless-stopped
    build: ./nginx
    volumes:
      - ./admin/dist:/www:ro
      - ./admin/server.conf:/etc/nginx/server.conf:ro
      - ./admin/ssl/ca.crt:/etc/nginx/ca.crt:ro
    networks:
      default:
      outside:
        ipv6_address: 2001:41d0:303:1f89:3:61b1:6a10:67
    ports:
      - 145.239.188.67:443:443

  portal-back-a:
    restart: unless-stopped
    build:
      context: ./portal
      dockerfile: Dockerfile.back
    networks:
      default:

  portal-back-b:
    restart: unless-stopped
    build:
      context: ./portal
      dockerfile: Dockerfile.back
    networks:
      default:

  portal-back-c:
    restart: unless-stopped
    build:
      context: ./portal
      dockerfile: Dockerfile.back
    networks:
      default:

  portal-front:
    restart: unless-stopped
    build: ./nginx
    links:
      - portal-back-a
      - portal-back-b
      - portal-back-c
    depends_on:
      - portal-back-a
      - portal-back-b
      - portal-back-c
    volumes:
      - ./portal/dist/front:/www:ro
      - ./portal/server.conf:/etc/nginx/server.conf:ro
    networks:
      default:
      outside:
        ipv6_address: 2001:41d0:303:1f89:3:61b1:6a10:64
    ports:
      - 145.239.188.64:443:443
      - 145.239.188.64:80:80

networks:
  outside:
    external: true

volumes:
  data-volume:
