
import {
  ArticleComponent,
  AuthDialogComponent,
  CoinComponent,
  CoinsRsibbonComponent,
  FooterComponent,
  HeaderComponent,
  LoaderComponent,
  NoContentComponent,
  Page101Component,
  Page404Component,
  PageArticleComponent,
  PageCoinComponent,
  PageCoinsComponent,
  PageDonateComponent,
  PageMainComponent,
  PagePrivacyComponent,
  PageTagComponent,
  PageTagsComponent,
  PageVideoComponent,
  PubCardComponent,
  PubLineComponent,
  SearchComponent,
  ShareComponent,
  TradingViewComponent,
  VideoRibbonComponent,
} from './components'

export const COMPONENTS: any[] = [
  ArticleComponent,
  AuthDialogComponent,
  CoinComponent,
  CoinsRsibbonComponent,
  FooterComponent,
  HeaderComponent,
  LoaderComponent,
  NoContentComponent,
  Page101Component,
  Page404Component,
  PageArticleComponent,
  PageCoinComponent,
  PageCoinsComponent,
  PageDonateComponent,
  PageMainComponent,
  PagePrivacyComponent,
  PageTagComponent,
  PageTagsComponent,
  PageVideoComponent,
  PubCardComponent,
  PubLineComponent,
  SearchComponent,
  ShareComponent,
  TradingViewComponent,
  VideoRibbonComponent,
]

export const ENTRY_COMPONENTS: any[] = [
  AuthDialogComponent,
  SearchComponent,
]
