
import {
  ArticleComponent,
  AuthDialogComponent,
  CurrenciesRsibbonComponent,
  FooterComponent,
  HeaderComponent,
  NoContentComponent,
  Page101Component,
  PageArticleComponent,
  PageCurrenciesComponent,
  PageCurrenciesItemComponent,
  PageEventsComponent,
  PageEventsItemComponent,
  PageExchangesComponent,
  PageExchangesItemComponent,
  PageICOComponent,
  PageICOItemComponent,
  PageMainComponent,
  PageMarketsComponent,
  PageMarketsItemComponent,
  PageSectionComponent,
  PubCardComponent,
  FollowComponent,
  VideoRibbonComponent,
  PubLineComponent,
} from './components'

export const COMPONENTS: any[] = [
  ArticleComponent,
  AuthDialogComponent,
  CurrenciesRsibbonComponent,
  FooterComponent,
  HeaderComponent,
  NoContentComponent,
  Page101Component,
  PageArticleComponent,
  PageCurrenciesComponent,
  PageCurrenciesItemComponent,
  PageEventsComponent,
  PageEventsItemComponent,
  PageExchangesComponent,
  PageExchangesItemComponent,
  PageICOComponent,
  PageICOItemComponent,
  PageMainComponent,
  PageMarketsComponent,
  PageMarketsItemComponent,
  PageSectionComponent,
  PubCardComponent,
  FollowComponent,
  VideoRibbonComponent,
  PubLineComponent,
]

export const ENTRY_COMPONENTS: any[] = [
  AuthDialogComponent,
]
