FROM node:carbon-alpine
MAINTAINER Wisdman <wisdman@ajaw.it>

COPY ./dist/back.js /app/back.js
COPY ./dist/index.html /app/index.html

RUN chmod +x /app/back.js

EXPOSE 80
WORKDIR /app

CMD ["/app/back.js"]
